version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "arga-todo-list-aws"
s3_bucket = "arga-deploy-bucket-default"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "arga-todo-list-aws-staging"
s3_bucket = "arga-deploy-bucket-staging"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "arga-todo-list-aws-production"
s3_bucket = "arga-deploy-bucket-production"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
